### ISSUE TITLE
Not working if send without boundary

### ISSUE THREAD

**Issue by maikschneider** [xima-media/xm_mail_catcher#22]
When reading the log file, the parser looks for a boundary to determine the different messages. When sending only HTML or TXT type mails, no boundary is set.

**Comment by JulianXIMA** [comment]
Hi, is this the reason for an error in JsonDateTime.php about return types (see: https://php.watch/versions/8.1/internal-method-return-types)?

If i add "ReturnTypeWillChange", it works for me:

```
#[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return $this->format('c');
    }
```

**Comment by maikschneider** [comment]
No. Use [dev-master](https://github.com/xima-media/xm_mail_catcher/commit/fd849d2c968116f5ae5c17ea209eeee64139e358) as long as no new version is released.
